services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "8082:81" # web console port
      - "9092:1521" # server port
    volumes:
      - h2_data:/opt/h2-data
    restart: always

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Shop
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:9092/shop
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - h2-database
    restart: always

volumes:
  h2_data: