spring:
  application:
    name: adapters
  datasource:
    url: jdbc:h2:mem:mydb
    username: h2
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
